import fs from 'node:fs';
import path from 'node:path';
import type { DevctxConfig } from '../config.ts';
import { repoContext, staleReason } from '../knowledge/anchors.ts';
import type { KnowledgeItem } from '../knowledge/types.ts';
import { loadTeam, saveStale } from '../knowledge/view.ts';
import type { StateDb } from '../state/db.ts';
import { assertSafeTarget, readText, writeFileAtomic } from '../util/fsx.ts';
import type { ProjectPaths } from '../util/paths.ts';
import { trackedGenerated } from '../init/attributes.ts';
import {
  AGENTS_BEGIN,
  AGENTS_END,
  GENERATED_MARKER,
  hasAgentsBlock,
  isLegacyAgentsMd,
  PATH_RULE_DIRS,
  renderAgentsBlock,
  renderOnDemandRules,
  renderPathRules,
  renderRulesMd,
  RULES_FILE,
  withAgentsBlock,
} from './render.ts';
import { isDeliverable, isExpired, planTiers, type TierPlan } from './tiers.ts';

export interface CompileResult {
  changed: string[];
  removed: string[];
  unchanged: string[];
  /** --check: files whose content differs from what would be generated. */
  drift: string[];
  warnings: string[];
  plan: TierPlan;
  /**
   * What happened to devctx's block in AGENTS.md. `legacy` and `outdated`: left as is because the
   * run was not an explicit one (a hook): the file is tracked, and changing it on checkout would
   * block the next checkout. `devctx init` or `devctx compile` writes it.
   */
  agents: 'unchanged' | 'updated' | 'migrated' | 'no-block' | 'legacy' | 'outdated';
}

// Sentences only an AGENTS.md generated by an earlier version had (ko, en).
const LEGACY_LINES = [
  '- 전체 결정과 이유는 `.devctx/knowledge/`에 있다.',
  '- 사용자가 규칙을 바꾸면 최신 지시를 따른다. 기록은 자동으로 갱신된다.',
  '- 경로별 규칙은 해당 파일을 다룰 때 도구별 규칙 파일로 적용된다.',
  '- All decisions and their reasons live in `.devctx/knowledge/`.',
  '- When the user changes a rule, follow the latest instruction. Records update automatically.',
  "- Path-specific rules are applied through each tool's rule files when matching files are touched.",
];

/**
 * A generated rule list left outside the block: an old branch's AGENTS.md merged with
 * `merge=union` (its `.gitattributes` still says so) keeps both sides' lines and drops the marker.
 */
export function legacyResidue(text: string | null): string | null {
  if (!text || !hasAgentsBlock(text)) return null;
  const outside = text.slice(0, text.indexOf(AGENTS_BEGIN)) + text.slice(text.indexOf(AGENTS_END) + AGENTS_END.length);
  if (outside.includes(GENERATED_MARKER)) return GENERATED_MARKER;
  return LEGACY_LINES.find((l) => outside.includes(l)) ?? null;
}

/** `devctx-*` files devctx generated in the tools' rule directories. */
export function existingGenerated(root: string): string[] {
  const out: string[] = [];
  for (const dir of PATH_RULE_DIRS) {
    let names: string[] = [];
    try {
      names = fs.readdirSync(path.join(root, dir));
    } catch {
      continue;
    }
    for (const name of names) {
      if (!name.startsWith('devctx-')) continue;
      const rel = `${dir}/${name}`;
      if (readText(path.join(root, rel))?.includes(GENERATED_MARKER)) out.push(rel);
    }
  }
  return out;
}

export interface RenderResult {
  outputs: Map<string, string>;
  plan: TierPlan;
  warnings: string[];
  items: KnowledgeItem[];
}

export function openConflicts(items: readonly KnowledgeItem[]): KnowledgeItem[] {
  return items.filter((i) => i.status === 'conflict' && i.audience === 'team' && !isExpired(i) && !i.held);
}

/**
 * The files each PC builds from the committed knowledge files (statuses derived from their links)
 * and the repository (code evidence): `.devctx/rules.md` and, with `toolFiles`, the tools' path
 * rule files. No local counters, so every clone at the same commit builds the same bytes. None of
 * them is committed.
 */
export function renderOutputs(
  paths: ProjectPaths,
  cfg: DevctxConfig,
  db: StateDb | null = null,
  opts: { items?: KnowledgeItem[]; toolFiles?: boolean } = {},
): RenderResult {
  let items: KnowledgeItem[];
  let warnings: string[] = [];
  if (opts.items) {
    // Already loaded, with the last compile's code-evidence results (no git calls here).
    items = opts.items;
  } else {
    const loaded = loadTeam(paths, db, { proposedTtlDays: cfg.memory.proposed_ttl_days });
    items = loaded.items;
    warnings = loaded.errors.map((e) => `${path.relative(paths.root, e.file)}: ${e.error}`);
    if (items.some((i) => i.anchors)) {
      const repo = repoContext(paths.root);
      for (const i of items) if (isDeliverable(i)) i.stale = staleReason(i, repo, cfg.language);
    }
    if (db) saveStale(db, items);
  }
  const plan = planTiers(items, cfg);
  if (plan.overflow.length > 0) {
    warnings.push(`core budget exceeded: ${plan.overflow.length} rule(s) moved to on-demand (inject.core_budget_tokens=${cfg.inject.core_budget_tokens})`);
  }
  const outputs = new Map<string, string>();
  outputs.set(RULES_FILE, renderRulesMd(plan, openConflicts(items), cfg.language));
  if (opts.toolFiles !== false) {
    for (const [rel, content] of renderPathRules(plan, cfg, cfg.targets)) outputs.set(rel, content);
    for (const [rel, content] of renderOnDemandRules(plan, cfg, cfg.targets)) outputs.set(rel, content);
  }
  return { outputs, plan, warnings, items };
}

/**
 * Keeps devctx's block in AGENTS.md current. The block changes only with the language, the code
 * index setting or a devctx upgrade, never with decisions. An AGENTS.md from before the block
 * (wholly generated) becomes the people's text from preamble.md plus the block.
 */
function syncAgents(paths: ProjectPaths, cfg: DevctxConfig, check: boolean, manual: boolean): CompileResult['agents'] {
  const current = readText(paths.agentsMd);
  const block = renderAgentsBlock(cfg.language, cfg.code_index.enabled);
  if (isLegacyAgentsMd(current)) {
    if (!manual) return 'legacy';
    if (check) return 'migrated';
    const preamble = (readText(paths.preamble) ?? '').trim();
    writeFileAtomic(paths.agentsMd, withAgentsBlock(preamble || null, block, cfg.language));
    // Its text now lives in AGENTS.md itself.
    fs.rmSync(paths.preamble, { force: true });
    return 'migrated';
  }
  if (!hasAgentsBlock(current)) return 'no-block';
  const next = withAgentsBlock(current, block, cfg.language);
  if (next === current) return 'unchanged';
  if (!manual) return 'outdated';
  if (!check) writeFileAtomic(paths.agentsMd, next);
  return 'updated';
}

/**
 * Builds `.devctx/rules.md` and (unless `toolFiles: false`) the tools' path rule files from
 * `.devctx/knowledge/`, and keeps devctx's block in AGENTS.md. Output is deterministic (sorted by
 * id), so unchanged knowledge never rewrites a file. The worker passes `toolFiles: false` at turn
 * ends: tools that send their rule files with every request keep the same files, and their prompt
 * cache, until the next session (new decisions reach the running session through the prompt hook).
 *
 * Runs from hooks (`manual` unset) never change a file git tracks: AGENTS.md, or rule files an
 * earlier version committed and an older branch still has. Rewriting them after a checkout would
 * leave local changes that block checking out the next branch. `devctx init` and `devctx compile`
 * pass `manual: true` and convert them.
 */
export function compile(
  paths: ProjectPaths,
  cfg: DevctxConfig,
  db: StateDb | null,
  opts: { check?: boolean; tool?: string; toolFiles?: boolean; manual?: boolean } = {},
): CompileResult {
  const toolFiles = opts.toolFiles !== false;
  const manual = Boolean(opts.manual);
  const { outputs, plan, warnings } = renderOutputs(paths, cfg, db, { toolFiles });
  const result: CompileResult = { changed: [], removed: [], unchanged: [], drift: [], warnings, plan, agents: 'unchanged' };
  result.agents = syncAgents(paths, cfg, Boolean(opts.check), manual);
  if (result.agents === 'no-block') warnings.push('AGENTS.md has no devctx block (run "devctx init" to add it)');
  if (result.agents === 'legacy') warnings.push('AGENTS.md was generated by an earlier devctx version (run "devctx init" to turn it into your text plus the devctx block)');
  if (result.agents === 'outdated') warnings.push('the devctx block in AGENTS.md is out of date (run "devctx compile")');
  const residue = legacyResidue(readText(paths.agentsMd));
  if (residue) {
    warnings.push(
      `AGENTS.md still has the rule list an earlier devctx version generated, outside the devctx block (${residue}), probably from merging an old branch. Delete it: rules now come from the session-start hook and .devctx/rules.md`,
    );
  }
  const tracked = manual ? new Set<string>() : new Set(trackedGenerated(paths.root));
  for (const rel of tracked) outputs.delete(rel);
  const stale = toolFiles ? existingGenerated(paths.root).filter((rel) => !outputs.has(rel) && !tracked.has(rel)) : [];

  if (opts.check) {
    for (const [rel, content] of outputs) {
      if (readText(path.join(paths.root, rel)) !== content) result.drift.push(rel);
    }
    result.drift.push(...stale);
    if (['updated', 'migrated', 'legacy', 'outdated'].includes(result.agents)) result.drift.push('AGENTS.md');
    return result;
  }

  for (const [rel, content] of outputs) {
    const file = path.join(paths.root, rel);
    if (readText(file) === content) {
      result.unchanged.push(rel);
    } else {
      assertSafeTarget(file, paths.root);
      writeFileAtomic(file, content);
      result.changed.push(rel);
    }
  }
  for (const rel of stale) {
    const file = path.join(paths.root, rel);
    assertSafeTarget(file, paths.root);
    fs.rmSync(file, { force: true });
    result.removed.push(rel);
  }
  if (result.agents === 'updated' || result.agents === 'migrated') result.changed.push('AGENTS.md');
  return result;
}
