import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { isMap, isSeq, parseDocument } from 'yaml';
import { CODE_TOOLS, usageLine } from '../codeindex/tools-meta.ts';
import type { Language, ToolId } from '../types.ts';
import { readText, sha256, writeFileAtomic } from '../util/fsx.ts';
import { git } from '../util/git.ts';

/**
 * How agents reach the code index: the `devctx-code` Agent Skill (repository files every tool
 * discovers) plus pre-approval of its one command prefix in each tool's permission settings, so
 * running a skill command never stops for an approval prompt.
 */

export const SKILL_NAME = 'devctx-code';
/** Command prefix the skill tells agents to run (from the repository root). */
export const CODE_COMMAND = '.devctx/bin/devctx code';
const MARKER = 'devctx:generated';

type Json = Record<string, unknown>;

export interface AccessResult {
  file: string;
  action: 'created' | 'updated' | 'unchanged' | 'removed' | 'skipped';
  note?: string;
}

function obj(v: unknown): Json {
  return v && typeof v === 'object' && !Array.isArray(v) ? (v as Json) : {};
}

function strings(v: unknown): string[] {
  return Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string') : [];
}

// ---- skill ----------------------------------------------------------------------------------

/**
 * Skill folders per tool. `.agents/skills` is read by Codex, Copilot (VS Code and CLI) and
 * Cursor; Claude Code reads `.claude/skills` (Copilot and Cursor read it too, so with both
 * present they list the same skill twice); Kiro reads `.kiro/skills`.
 */
function skillFiles(tools: readonly ToolId[]): { rel: string; claude: boolean }[] {
  const out: { rel: string; claude: boolean }[] = [];
  if (tools.includes('claude')) out.push({ rel: `.claude/skills/${SKILL_NAME}/SKILL.md`, claude: true });
  if (tools.some((t) => t === 'codex' || t === 'copilot' || t === 'cursor')) out.push({ rel: `.agents/skills/${SKILL_NAME}/SKILL.md`, claude: false });
  if (tools.includes('kiro')) out.push({ rel: `.kiro/skills/${SKILL_NAME}/SKILL.md`, claude: false });
  return out;
}

const ALL_SKILL_FILES = [`.claude/skills/${SKILL_NAME}/SKILL.md`, `.agents/skills/${SKILL_NAME}/SKILL.md`, `.kiro/skills/${SKILL_NAME}/SKILL.md`];

const DESCRIPTION =
  'Code index of this repository: find where classes, functions and components are defined, who calls them, what they call, ' +
  'file outlines, an architecture overview and the impact of uncommitted changes, by running `.devctx/bin/devctx code <tool>`. ' +
  'Use it before grepping or opening many files, and whenever you need to know where something is defined or used, how code ' +
  'is connected, or what a change can break. Also earlier work in this repository (search_history: past requests, what was tried ' +
  'and how it ended, replaced decisions and why). (코드 탐색: 정의, 사용처, 호출 관계, 파일 구조, 변경 영향, 이전 작업)';

export function renderSkill(lang: Language, claude: boolean): string {
  const front = [
    '---',
    `name: ${SKILL_NAME}`,
    `description: ${JSON.stringify(DESCRIPTION)}`,
    // Claude Code only: no approval prompt for the skill's commands while it is active.
    ...(claude ? [`allowed-tools: Bash(${CODE_COMMAND} *), Bash(./${CODE_COMMAND} *)`] : []),
    '---',
  ];
  const rows = CODE_TOOLS.map((t) => `| \`${usageLine(t, CODE_COMMAND)}\` | ${t.summary[lang]} |`);
  const body =
    lang === 'ko'
      ? [
          `<!-- ${MARKER}: devctx가 만든 파일이다. 직접 고치지 말 것 (devctx init / 세션 시작 때 다시 생성) -->`,
          '',
          '# 코드 인덱스 (devctx)',
          '',
          '이 저장소의 심볼, 호출 관계, 변경 영향을 미리 색인해 둔 명령이다. grep으로 훑거나 파일을 여러 개 열기 전에 먼저 쓴다.',
          '',
          '## 실행 규칙',
          '',
          `- 저장소 루트에서 명령 하나씩 실행한다: \`${CODE_COMMAND} <도구> <인자>\`.`,
          '- 파이프(`|`), `&&`, `;`, 리다이렉트를 붙이지 않는다. 결과는 이미 짧게 정리돼 나오고, 붙이면 미리 허용된 명령으로 인식되지 않아 승인을 묻는다.',
          '- 공백이 있는 인자는 따옴표로 감싼다. 첫 인자는 위치 인자로, 나머지는 `--이름 값`으로 준다.',
          '- 명령이 답하기 전에 바뀐 파일만 다시 색인하므로 방금 고친 코드도 반영된다.',
          '',
          '## 도구',
          '',
          '| 명령 | 용도 |',
          '|---|---|',
          ...rows,
          '',
          '## 결과 읽기',
          '',
          '- 결과는 `path:line` 형식이다. 전체 파일 대신 필요한 줄만 읽는다.',
          '- `(by name)`이 붙은 연결은 import나 타입 근거 없이 이름만 보고 이은 것이다. 수정 근거로 쓰기 전에 코드를 확인한다.',
          '- 리플렉션, 동적 디스패치, 프레임워크가 대신 부르는 코드는 빠질 수 있다. 그럴 땐 `search_text`로 확인한다.',
          '- 종료 코드 1은 요청이 잘못됐다는 뜻이다(모르는 옵션·값, 잘못된 정규식, 없는 브랜치). 메시지대로 고쳐 다시 실행한다. 결과가 없는 것은 오류가 아니다(종료 코드 0).',
          '- 명령을 쓸 수 없으면 평소처럼 파일을 읽는다.',
          '',
          '## 예시',
          '',
          ...CODE_TOOLS.slice(0, 4).map((t) => `- \`${CODE_COMMAND} ${t.example}\``),
          `- 수정 후 커밋 전: \`${CODE_COMMAND} change_impact\``,
        ]
      : [
          `<!-- ${MARKER}: written by devctx; do not edit (regenerated by devctx init and at session start) -->`,
          '',
          '# Code index (devctx)',
          '',
          "Pre-built index of this repository's symbols, call graph and change impact. Use it before grepping or opening many files.",
          '',
          '## How to run',
          '',
          `- Run one command at a time from the repository root: \`${CODE_COMMAND} <tool> <args>\`.`,
          '- Do not add pipes (`|`), `&&`, `;` or redirects. Output is already compact, and a compound command no longer matches the pre-approved prefix, so it asks for approval.',
          '- Quote arguments that contain spaces. The first argument is positional, the rest are `--name value`.',
          '- Each command re-indexes only changed files before answering, so code you just edited is included.',
          '',
          '## Tools',
          '',
          '| Command | Purpose |',
          '|---|---|',
          ...rows,
          '',
          '## Reading results',
          '',
          '- Results are `path:line`; read just those lines instead of whole files.',
          '- Links marked `(by name)` were matched by name only (no import or type evidence); check the code before relying on them.',
          '- Reflection, dynamic dispatch and framework-invoked code can be missing; confirm with `search_text`.',
          '- Exit status 1 means the request was wrong (unknown option or value, bad regex, unknown revision): fix it as the message says and run again. No results is not an error (exit 0).',
          '- If the command is unavailable, read files as usual.',
          '',
          '## Examples',
          '',
          ...CODE_TOOLS.slice(0, 4).map((t) => `- \`${CODE_COMMAND} ${t.example}\``),
          `- After editing, before committing: \`${CODE_COMMAND} change_impact\``,
        ];
  return `${[...front, ...body].join('\n')}\n`;
}

function writeOwned(root: string, rel: string, content: string | null): AccessResult {
  const file = path.join(root, rel);
  const current = readText(file);
  if (content === null) {
    if (current === null) return { file: rel, action: 'unchanged' };
    if (!current.includes(MARKER)) return { file: rel, action: 'skipped', note: 'not written by devctx; left in place' };
    fs.rmSync(file, { force: true });
    try {
      fs.rmdirSync(path.dirname(file)); // only when empty
    } catch {
      // other files in the skill folder
    }
    return { file: rel, action: 'removed' };
  }
  if (current === content) return { file: rel, action: 'unchanged' };
  if (current !== null && !current.includes(MARKER)) return { file: rel, action: 'skipped', note: 'a file devctx did not write is in the way' };
  writeFileAtomic(file, content);
  return { file: rel, action: current === null ? 'created' : 'updated' };
}

// ---- JSON settings files ---------------------------------------------------------------------

/** JSON with comments and trailing commas (VS Code and Cursor settings) to plain JSON text. */
function stripJsonc(text: string): string {
  return text
    .replace(/("(?:[^"\\]|\\.)*")|\/\/[^\n]*|\/\*[\s\S]*?\*\//g, (_m, s: string | undefined) => s ?? '')
    .replace(/,(\s*[}\]])/g, '$1');
}

/**
 * Edits a JSON settings file in place, keeping every other key. Files with comments are left
 * alone (rewriting would drop them) unless they already contain what devctx wants.
 */
function editJson(root: string, rel: string, mutate: (data: Json) => void, opts: { create: boolean; absolute?: boolean }): AccessResult {
  const file = opts.absolute ? rel : path.join(root, rel);
  const text = readText(file);
  let data: Json = {};
  if (text === null) {
    if (!opts.create) return { file: rel, action: 'unchanged' };
  } else {
    try {
      const parsed: unknown = JSON.parse(text);
      if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return { file: rel, action: 'skipped', note: 'not a JSON object; left untouched' };
      data = parsed as Json;
    } catch {
      let loose: Json | null = null;
      try {
        loose = obj(JSON.parse(stripJsonc(text)));
      } catch {
        return { file: rel, action: 'skipped', note: 'not valid JSON; left untouched' };
      }
      const before = JSON.stringify(loose);
      mutate(loose);
      if (JSON.stringify(loose) === before) return { file: rel, action: 'unchanged' };
      return { file: rel, action: 'skipped', note: 'has comments; add the devctx entry by hand (see "devctx code status")' };
    }
  }
  const before = JSON.stringify(data);
  mutate(data);
  if (JSON.stringify(data) === before) return { file: rel, action: 'unchanged' };
  if (Object.keys(data).length === 0) {
    fs.rmSync(file, { force: true });
    return { file: rel, action: 'removed' };
  }
  writeFileAtomic(file, `${JSON.stringify(data, null, 2)}\n`);
  return { file: rel, action: text === null ? 'created' : 'updated' };
}

/** Adds (or removes) `values` in the string array at `holder[key]`, dropping the key when empty. */
function setStrings(holder: Json, key: string, values: readonly string[], enabled: boolean): void {
  const list = strings(holder[key]);
  const next = enabled ? [...list, ...values.filter((v) => !list.includes(v))] : list.filter((v) => !values.includes(v));
  if (next.length === 0) delete holder[key];
  else if (next.length !== list.length || !Array.isArray(holder[key])) holder[key] = next;
}

function nested(data: Json, key: string): Json {
  const value = obj(data[key]);
  data[key] = value;
  return value;
}

function dropEmpty(data: Json, key: string): void {
  if (Object.keys(obj(data[key])).length === 0) delete data[key];
}

const CLAUDE_RULES = [`Bash(${CODE_COMMAND} *)`, `Bash(./${CODE_COMMAND} *)`];

/** Claude Code: project `.claude/settings.json` permission rules (the hooks live in the same file). */
const claudeEdit =
  (enabled: boolean) =>
  (d: Json): void => {
    const perms = nested(d, 'permissions');
    setStrings(perms, 'allow', CLAUDE_RULES, enabled);
    dropEmpty(d, 'permissions');
  };

function claudeSettings(root: string, enabled: boolean): AccessResult {
  return editJson(root, '.claude/settings.json', claudeEdit(enabled), { create: enabled });
}

const VSCODE_KEY = 'chat.tools.terminal.autoApprove';
const VSCODE_RULE = '/^(\\./)?\\.devctx/bin/devctx code(\\s|$)/';

/** Copilot in VS Code: terminal auto-approval rules in the workspace settings (trusted workspaces). */
const vscodeEdit =
  (enabled: boolean) =>
  (d: Json): void => {
    const rules = nested(d, VSCODE_KEY);
    if (enabled) rules[VSCODE_RULE] = true;
    else delete rules[VSCODE_RULE];
    dropEmpty(d, VSCODE_KEY);
  };

function vscodeSettings(root: string, enabled: boolean): AccessResult {
  return editJson(root, '.vscode/settings.json', vscodeEdit(enabled), { create: enabled });
}

const CURSOR_INSTRUCTION = `Commands that start with \`${CODE_COMMAND}\` are read-only queries of this repository's code index (search_symbols, get_symbol, trace_calls, file_outline, repo_overview, change_impact, search_text); allow them.`;

function cursorUserAllowlist(): boolean {
  const text = readText(path.join(os.homedir(), '.cursor', 'permissions.json'));
  if (!text) return false;
  try {
    return Array.isArray(obj(JSON.parse(stripJsonc(text))).terminalAllowlist);
  } catch {
    return false;
  }
}

/**
 * Cursor IDE: `.cursor/permissions.json`. A `terminalAllowlist` there replaces each user's own
 * in-app allowlist, so devctx only appends to one that is already file-controlled; otherwise it
 * steers the Auto-review classifier, which merges with personal settings.
 */
const cursorEdit =
  (enabled: boolean, userList: boolean) =>
  (d: Json): void => {
    if (Array.isArray(d.terminalAllowlist) || (userList && enabled)) setStrings(d, 'terminalAllowlist', [CODE_COMMAND], enabled);
    const auto = nested(d, 'autoRun');
    setStrings(auto, 'allow_instructions', [CURSOR_INSTRUCTION], enabled);
    dropEmpty(d, 'autoRun');
  };

function cursorPermissions(root: string, enabled: boolean): AccessResult {
  return editJson(root, '.cursor/permissions.json', cursorEdit(enabled, cursorUserAllowlist()), { create: enabled });
}

/** Cursor CLI: `.cursor/cli.json` shadows the global CLI config, so it is only extended, never created. */
function cursorCli(root: string, enabled: boolean): AccessResult {
  return editJson(
    root,
    '.cursor/cli.json',
    (d) => {
      const perms = nested(d, 'permissions');
      setStrings(perms, 'allow', [`Shell(${CODE_COMMAND.replace(' ', ':')} *)`], enabled);
      dropEmpty(d, 'permissions');
    },
    { create: false },
  );
}

// ---- Codex ----------------------------------------------------------------------------------

function codexRules(): string {
  return `# ${MARKER}: written by devctx init. Lets Codex run the devctx-code skill's commands
# (read-only code index queries) without an approval prompt. Loaded for trusted projects.
prefix_rule(
    pattern = [[".devctx/bin/devctx", "./.devctx/bin/devctx"], "code"],
    decision = "allow",
    justification = "devctx code index queries; they only update .devctx/local",
    match = [
        ".devctx/bin/devctx code search_symbols OrderService",
        "./.devctx/bin/devctx code get_symbol OrderService.place",
    ],
    not_match = [
        ".devctx/bin/devctx init",
        "devctx code search_symbols OrderService",
    ],
)
`;
}

// ---- per-machine permission files --------------------------------------------------------------

/** Copilot CLI keys saved approvals by the main repository root (linked worktrees share it). */
function mainRepoRoot(root: string): string {
  const r = git(['rev-parse', '--path-format=absolute', '--git-common-dir'], root, 5_000);
  if (r.ok && r.stdout && path.basename(r.stdout) === '.git') return path.dirname(r.stdout);
  return path.resolve(root);
}

const COPILOT_IDS = [`${CODE_COMMAND}:*`, `./${CODE_COMMAND}:*`];

/**
 * Copilot CLI reads saved approvals only from `~/.copilot/permissions-config.json`, keyed by
 * repository path (no repository-level file exists), so each machine gets its own entry.
 */
function copilotCliPermissions(root: string, enabled: boolean): AccessResult {
  const home = process.env.COPILOT_HOME ? path.resolve(process.env.COPILOT_HOME) : path.join(os.homedir(), '.copilot');
  const file = path.join(home, 'permissions-config.json');
  if (!fs.existsSync(home)) return { file, action: 'unchanged' };
  const key = mainRepoRoot(root);
  return editJson(
    root,
    file,
    (d) => {
      const locations = obj(d.locations);
      const loc = obj(locations[key]);
      const approvals = Array.isArray(loc.tool_approvals) ? (loc.tool_approvals as unknown[]).map(obj) : [];
      const has = approvals.some((a) => a.kind === 'commands' && COPILOT_IDS.every((id) => strings(a.commandIdentifiers).includes(id)));
      if (enabled === has) return;
      const next = enabled
        ? [...approvals, { kind: 'commands', commandIdentifiers: [...COPILOT_IDS] }]
        : approvals
            .map((a) => (a.kind === 'commands' ? { ...a, commandIdentifiers: strings(a.commandIdentifiers).filter((id) => !COPILOT_IDS.includes(id)) } : a))
            .filter((a) => a.kind !== 'commands' || strings(a.commandIdentifiers).length > 0);
      if (next.length > 0) loc.tool_approvals = next;
      else delete loc.tool_approvals;
      if (Object.keys(loc).length > 0) locations[key] = loc;
      else delete locations[key];
      if (Object.keys(locations).length > 0) d.locations = locations;
      else delete d.locations;
    },
    { create: enabled, absolute: true },
  );
}

const KIRO_MATCH = [`${CODE_COMMAND} *`, `./${CODE_COMMAND} *`];

/**
 * Kiro keeps workspace permission rules outside the repository, in
 * `~/.kiro/workspace-roots/<first 16 hex of sha256(workspace path)>/permissions.yaml`.
 */
export function kiroPermissionsFile(root: string): string {
  const home = process.env.KIRO_HOME ? path.resolve(process.env.KIRO_HOME) : path.join(os.homedir(), '.kiro');
  return path.join(home, 'workspace-roots', sha256(path.resolve(root)).slice(0, 16), 'permissions.yaml');
}

function kiroPermissions(root: string, enabled: boolean): AccessResult {
  const file = kiroPermissionsFile(root);
  const home = path.dirname(path.dirname(path.dirname(file)));
  if (!fs.existsSync(home)) return { file, action: 'unchanged' };
  const text = readText(file);
  if (text === null && !enabled) return { file, action: 'unchanged' };
  const doc = parseDocument(text ?? 'rules: []\n');
  if (doc.errors.length > 0) return { file, action: 'skipped', note: 'not valid YAML; left untouched' };
  let rules = doc.get('rules');
  if (!isSeq(rules)) {
    doc.set('rules', doc.createNode([]));
    rules = doc.get('rules');
  }
  if (!isSeq(rules)) return { file, action: 'skipped', note: 'unexpected layout' };
  const ours = (item: unknown): boolean => {
    if (!isMap(item)) return false;
    const match = item.get('match');
    const list = isSeq(match) ? match.items.map((m) => String((m as { value?: unknown }).value ?? m)) : [];
    return item.get('capability') === 'shell' && item.get('effect') === 'allow' && KIRO_MATCH.every((m) => list.includes(m));
  };
  const present = rules.items.some(ours);
  if (enabled === present) return { file, action: 'unchanged' };
  if (enabled) {
    const rule = doc.createNode({ capability: 'shell', effect: 'allow', match: [...KIRO_MATCH] });
    rules.flow = false; // the block style Kiro itself writes
    rules.add(rule);
  } else rules.items = rules.items.filter((i) => !ours(i));
  const empty = rules.items.length === 0 && isMap(doc.contents) && doc.contents.items.length === 1;
  if (empty) {
    fs.rmSync(file, { force: true });
    try {
      fs.rmdirSync(path.dirname(file)); // the workspace folder, when devctx created it
    } catch {
      // Kiro keeps other state there
    }
    return { file, action: 'removed' };
  }
  writeFileAtomic(file, String(doc));
  return { file, action: enabled ? (text === null ? 'created' : 'updated') : 'removed' };
}

// ---- entry points ------------------------------------------------------------------------------

export interface AccessOptions {
  /** Code index on: skills are installed; off: removed. */
  enabled: boolean;
  /** Also pre-approve the command (config `code_index.preapprove`). */
  preapprove: boolean;
  language: Language;
}

/** Repository files: skills and the permission settings tools read from the repository. */
export function installRepoAccess(root: string, tools: readonly ToolId[], opts: AccessOptions): AccessResult[] {
  const wanted = new Map(skillFiles(opts.enabled ? tools : []).map((s) => [s.rel, renderSkill(opts.language, s.claude)]));
  const results = ALL_SKILL_FILES.map((rel) => writeOwned(root, rel, wanted.get(rel) ?? null));
  const allow = opts.enabled && opts.preapprove;
  const has = (t: ToolId): boolean => allow && tools.includes(t);
  results.push(claudeSettings(root, has('claude')));
  results.push(writeOwned(root, '.codex/rules/devctx.rules', has('codex') ? codexRules() : null));
  results.push(vscodeSettings(root, has('copilot')));
  results.push(cursorPermissions(root, has('cursor')));
  results.push(cursorCli(root, has('cursor')));
  return results;
}

/**
 * Per-machine permission files (Copilot CLI, Kiro): written by `devctx init` and re-checked at
 * session start, so a teammate's clone gets them without running anything.
 */
export function installMachineAccess(root: string, tools: readonly ToolId[], opts: AccessOptions): AccessResult[] {
  const allow = opts.enabled && opts.preapprove;
  const results: AccessResult[] = [];
  if (tools.includes('copilot') || !allow) results.push(copilotCliPermissions(root, allow && tools.includes('copilot')));
  if (tools.includes('kiro') || !allow) results.push(kiroPermissions(root, allow && tools.includes('kiro')));
  return results;
}

export function installAgentAccess(root: string, tools: readonly ToolId[], opts: AccessOptions): AccessResult[] {
  return [...installRepoAccess(root, tools, opts), ...installMachineAccess(root, tools, opts)];
}

/**
 * Why init could not add devctx's entry to a JSON settings file, and what to add by hand: devctx
 * never rewrites a file with comments (they would be lost), so running init again does not help.
 */
function jsonHint(file: string, mutate: (d: Json) => void, ok: boolean): string | undefined {
  const text = ok ? null : readText(file);
  if (text === null) return undefined;
  try {
    JSON.parse(text);
    return undefined;
  } catch {
    // comments or broken
  }
  try {
    JSON.parse(stripJsonc(text));
  } catch {
    return 'not valid JSON: fix it, then run "devctx init"';
  }
  const want: Json = {};
  mutate(want);
  return `has comments, so devctx does not rewrite it ("devctx init" will not help). Merge this in by hand: ${JSON.stringify(want)}`;
}

export interface AccessStatus {
  file: string;
  ok: boolean;
  /** What to do when the fix is not "run devctx init". */
  hint?: string;
}

/** What `devctx doctor` / `devctx code status` report: expected files and whether they are in place. */
export function agentAccessStatus(root: string, tools: readonly ToolId[], opts: AccessOptions): AccessStatus[] {
  if (!opts.enabled) return [];
  const out: AccessStatus[] = skillFiles(tools).map((s) => ({ file: s.rel, ok: readText(path.join(root, s.rel)) === renderSkill(opts.language, s.claude) }));
  if (!opts.preapprove) return out;
  const contains = (file: string, needle: string): boolean => (readText(file) ?? '').includes(needle);
  const json = (rel: string, needle: string, mutate: (d: Json) => void): AccessStatus => {
    const file = path.join(root, rel);
    const ok = contains(file, needle);
    const hint = jsonHint(file, mutate, ok);
    return hint ? { file: rel, ok, hint } : { file: rel, ok };
  };
  if (tools.includes('claude')) out.push(json('.claude/settings.json', CLAUDE_RULES[0] as string, claudeEdit(true)));
  if (tools.includes('codex')) out.push({ file: '.codex/rules/devctx.rules', ok: readText(path.join(root, '.codex/rules/devctx.rules')) === codexRules() });
  if (tools.includes('copilot')) out.push(json('.vscode/settings.json', 'devctx/bin/devctx code', vscodeEdit(true)));
  if (tools.includes('cursor')) out.push(json('.cursor/permissions.json', CODE_COMMAND, cursorEdit(true, cursorUserAllowlist())));
  if (tools.includes('kiro') && fs.existsSync(path.dirname(path.dirname(path.dirname(kiroPermissionsFile(root)))))) {
    out.push({ file: '~/.kiro/workspace-roots/…/permissions.yaml', ok: contains(kiroPermissionsFile(root), KIRO_MATCH[0] as string) });
  }
  return out;
}

// ---- the MCP server devctx registered before the skill ---------------------------------------------

const LEGACY_SERVER = 'devctx-code';
const TOML_BEGIN = '# >>> devctx >>>';
const TOML_END = '# <<< devctx <<<';

/** Removes the `devctx-code` MCP server earlier versions registered (every tool's project file). */
export function removeLegacyMcp(root: string): AccessResult[] {
  const results: AccessResult[] = [];
  for (const [rel, key] of [
    ['.mcp.json', 'mcpServers'],
    ['.vscode/mcp.json', 'servers'],
    ['.cursor/mcp.json', 'mcpServers'],
    ['.kiro/settings/mcp.json', 'mcpServers'],
  ] as const) {
    results.push(
      editJson(
        root,
        rel,
        (d) => {
          const servers = obj(d[key]);
          if (!(LEGACY_SERVER in servers)) return;
          delete servers[LEGACY_SERVER];
          d[key] = servers;
          if (Object.keys(servers).length === 0) delete d[key];
        },
        { create: false },
      ),
    );
  }
  const rel = '.codex/config.toml';
  const file = path.join(root, rel);
  const text = readText(file);
  const start = text?.indexOf(TOML_BEGIN) ?? -1;
  const end = text?.indexOf(TOML_END) ?? -1;
  if (text !== null && start >= 0 && end > start && text.slice(start, end).includes(`mcp_servers.${LEGACY_SERVER}`)) {
    const rest = `${text.slice(0, start)}${text.slice(end + TOML_END.length)}`.replace(/\n{3,}/g, '\n\n').trim();
    if (rest) writeFileAtomic(file, `${rest}\n`);
    else fs.rmSync(file, { force: true });
    results.push({ file: rel, action: 'removed' });
  }
  return results
    .filter((r) => r.action !== 'unchanged')
    .map((r) => (r.action === 'skipped' ? r : { ...r, note: 'removed the devctx-code MCP server (replaced by the skill)' }));
}
