import path from 'node:path';
import { readJson, readText } from '../util/fsx.ts';
import { packageRoot } from '../util/paths.ts';

export interface ToolsLock {
  version: string;
  source: string;
}

export function packageInfo(): { name: string; version: string } {
  const pkg = readJson<{ name?: string; version?: string }>(path.join(packageRoot(), 'package.json'), {});
  return { name: pkg.name ?? 'devctx', version: pkg.version ?? '0.0.0' };
}

/**
 * Where teammates' shims install devctx from. A local checkout is recorded as a path (works on
 * this machine only); an installed package as `<name>@<version>`.
 */
export function defaultSource(): string {
  const root = packageRoot();
  if (root.split(path.sep).includes('node_modules')) {
    const { name, version } = packageInfo();
    return `${name}@${version}`;
  }
  return root;
}

export function renderToolsLock(lock: ToolsLock): string {
  return `# devctx 실행 파일 고정 (Git으로 공유). clone만 하면 .devctx/bin/devctx가 이 버전을 찾거나 설치한다.
devctx_version: ${lock.version}
# npm 스펙(@scope/devctx@1.2.3), git URL(github:owner/repo#v1.2.3) 또는 이 머신의 로컬 경로
devctx_source: ${lock.source}
`;
}

export function parseToolsLock(text: string | null): ToolsLock | null {
  if (!text) return null;
  const get = (key: string): string =>
    (text.match(new RegExp(`^${key}:\\s*(.*)$`, 'm'))?.[1] ?? '').replace(/\s+#.*$/, '').replace(/^["']|["']$/g, '').trim();
  const version = get('devctx_version');
  const source = get('devctx_source');
  return version || source ? { version, source } : null;
}

export function readToolsLock(file: string): ToolsLock | null {
  return parseToolsLock(readText(file));
}

/**
 * POSIX shim committed at `.devctx/bin/devctx`. It finds node (IDEs launched from the Dock often
 * lack the shell PATH) and the pinned CLI; on a fresh clone it installs the pinned version in the
 * background. In hook mode it never fails or blocks the AI tool.
 */
export function renderShim(): string {
  return `#!/bin/sh
# devctx shim (generated by "devctx init", commit it). Runs the devctx version pinned in
# .devctx/tools.lock. Hook calls never fail or block the AI tool.
is_hook=0
[ "\${1:-}" = "hook" ] && is_hook=1
if [ "$is_hook" = 1 ] && [ -n "\${DEVCTX_INTERNAL:-}" ]; then exit 0; fi

hook_fallback() {
  # Cursor's beforeSubmitPrompt expects {"continue": true}.
  case " $* " in *" --tool cursor "*"--event prompt"*) printf '{"continue":true}' ;; esac
  exit 0
}

root=$(CDPATH= cd -- "$(dirname -- "$0")/../.." 2>/dev/null && pwd)
lock="$root/.devctx/tools.lock"
version=$(sed -n 's/^devctx_version:[[:space:]]*//p' "$lock" 2>/dev/null | sed 's/[[:space:]][[:space:]]*#.*$//' | tr -d '"'"'"'\\r ')
source=$(sed -n 's/^devctx_source:[[:space:]]*//p' "$lock" 2>/dev/null | sed 's/[[:space:]][[:space:]]*#.*$//' | tr -d '"'"'"'\\r')
data="\${DEVCTX_HOME:-\${XDG_DATA_HOME:-$HOME/.local/share}/devctx}"

find_node() {
  if command -v node >/dev/null 2>&1; then command -v node; return 0; fi
  best=""
  for n in "$HOME"/.nvm/versions/node/*/bin/node; do [ -x "$n" ] && best="$n"; done
  if [ -n "$best" ]; then echo "$best"; return 0; fi
  for n in /opt/homebrew/bin/node /usr/local/bin/node "$HOME/.volta/bin/node" /usr/bin/node; do
    if [ -x "$n" ]; then echo "$n"; return 0; fi
  done
  return 1
}

if ! node_bin=$(find_node); then
  [ "$is_hook" = 1 ] && hook_fallback "$@"
  echo "devctx: node >= 22.13 not found" >&2
  exit 1
fi

cli=""
for c in "\${DEVCTX_CLI:-}" \\
  "$data/versions/$version/node_modules/devctx/dist/cli.js" \\
  "$data/versions/$version"/node_modules/@*/devctx/dist/cli.js \\
  "$source/dist/cli.js" \\
  "$source/src/cli.ts" \\
  "$root/node_modules/devctx/dist/cli.js"; do
  if [ -n "$c" ] && [ -f "$c" ]; then cli="$c"; break; fi
done

if [ -z "$cli" ]; then
  installable=1
  if [ -z "$source" ] || [ -d "$source" ]; then installable=0; fi
  # A local path that is missing here (e.g. someone else's checkout) can't be installed either;
  # without this every hook call would spawn a failing npm install.
  case "$source" in /*|./*|../*) [ -e "$source" ] || installable=0 ;; esac
  if [ "$installable" = 0 ]; then
    [ "$is_hook" = 1 ] && hook_fallback "$@"
    echo "devctx: CLI not found. Set devctx_source in .devctx/tools.lock to an npm spec or git URL" >&2
    exit 1
  fi
  npm_bin="$(dirname "$node_bin")/npm"
  [ -x "$npm_bin" ] || npm_bin=npm
  target="$data/versions/$version"
  if [ "$is_hook" = 1 ]; then
    # First run on this machine: install in the background, the next hook call will use it.
    ( mkdir -p "$target" && "$npm_bin" install --prefix "$target" --no-save --no-audit --no-fund --silent "$source" ) </dev/null >/dev/null 2>&1 &
    hook_fallback "$@"
  fi
  mkdir -p "$target" && "$npm_bin" install --prefix "$target" --no-save --no-audit --no-fund "$source" >&2 || exit 1
  for c in "$target/node_modules/devctx/dist/cli.js" "$target"/node_modules/@*/devctx/dist/cli.js; do
    [ -f "$c" ] && cli="$c" && break
  done
  [ -n "$cli" ] || { echo "devctx: installed package has no dist/cli.js" >&2; exit 1; }
fi

exec "$node_bin" --disable-warning=ExperimentalWarning "$cli" "$@"
`;
}
